import type { AppQuestion } from './types';

export const questions: AppQuestion[] = [
  // Level 1: Easy, Multiple Choice
  {
    id: '1',
    level: 1,
    type: 'multiple-choice',
    text: 'The girl ___ is smiling is my sister.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'who',
    difficulty: 'easy',
  },
  {
    id: '2',
    level: 1,
    type: 'multiple-choice',
    text: 'This is the cake ___ I bought yesterday.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'that',
    difficulty: 'easy',
  },
  {
    id: '3',
    level: 1,
    type: 'true-false',
    text: "Is this sentence correct? 'The car who is red is fast.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'easy',
  },
  {
    id: '4',
    level: 1,
    type: 'multiple-choice',
    text: 'Do you know the woman ___ lives next door?',
    options: ['who', 'which', 'that'],
    correctAnswer: 'who',
    difficulty: 'easy',
  },
  {
    id: '5',
    level: 1,
    type: 'multiple-choice',
    text: 'The phone ___ I lost was new.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'which',
    difficulty: 'easy',
  },
  // Level 2: Intermediate, Fill-in-the-blank
  {
    id: '6',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'She is the artist ___ paintings are famous worldwide.',
    options: ['who', 'whose', 'which'],
    correctAnswer: 'whose',
    difficulty: 'medium',
  },
  {
    id: '7',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'I visited the town ___ my father was born.',
    options: ['that', 'where', 'who'],
    correctAnswer: 'where',
    difficulty: 'medium',
  },
  {
    id: '8',
    level: 2,
    type: 'true-false',
    text: "Is this sentence correct? 'The movie, that I saw last night, was boring.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'medium',
  },
  {
    id: '9',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'The reason ___ I am late is because of traffic.',
    options: ['why', 'which', 'who'],
    correctAnswer: 'why',
    difficulty: 'medium',
  },
  {
    id: '10',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'He finally met the celebrity ___ he had always admired.',
    options: ['which', 'that', 'whom'],
    correctAnswer: 'whom',
    difficulty: 'medium',
  },
  // Level 3: Advanced, Timed
  {
    id: '11',
    level: 3,
    type: 'timed-choice',
    text: 'The project, ___ was completed ahead of schedule, received high praise.',
    options: ['which', 'that', 'who'],
    correctAnswer: 'which',
    difficulty: 'hard',
  },
  {
    id: '12',
    level: 3,
    type: 'timed-choice',
    text: 'This is the only one of his books ___ is worth reading.',
    options: ['which', 'that', 'who'],
    correctAnswer: 'that',
    difficulty: 'hard',
  },
  {
    id: '13',
    level: 3,
    type: 'true-false',
    text: "Is this sentence correct? 'The students whom passed the exam were thrilled.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'hard',
  },
  {
    id: '14',
    level: 3,
    type: 'timed-choice',
    text: "I talked to the person ___ car was blocking the driveway.",
    options: ['who', 'whose', 'which'],
    correctAnswer: 'whose',
    difficulty: 'hard',
  },
  {
    id: '15',
    level: 3,
    type: 'timed-choice',
    text: 'The decisions ___ the committee makes are final.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'that',
    difficulty: 'hard',
  },
];
