import type { AppQuestion } from './types';

export const questions: AppQuestion[] = [
  // Level 1: Easy, Multiple Choice
  {
    id: '1',
    level: 1,
    type: 'multiple-choice',
    text: 'The girl ___ is smiling is my sister.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'who',
    difficulty: 'easy',
    explanation: 'Use "who" for people.',
  },
  {
    id: '2',
    level: 1,
    type: 'multiple-choice',
    text: 'This is the cake ___ I bought yesterday.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'that',
    difficulty: 'easy',
    explanation: 'Use "that" or "which" for things. "That" is very common.',
  },
  {
    id: '3',
    level: 1,
    type: 'true-false',
    text: "Is this sentence correct? 'The car who is red is fast.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'easy',
    explanation: '"Who" is used for people. For a car, you should use "that" or "which".',
  },
  {
    id: '4',
    level: 1,
    type: 'multiple-choice',
    text: 'Do you know the woman ___ lives next door?',
    options: ['who', 'which', 'that'],
    correctAnswer: 'who',
    difficulty: 'easy',
    explanation: 'Use "who" to refer to people.',
  },
  {
    id: '5',
    level: 1,
    type: 'multiple-choice',
    text: 'The phone ___ I lost was new.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'which',
    difficulty: 'easy',
    explanation: 'Use "which" or "that" for things. "Which" is often used for non-essential information, but is correct here too.',
  },
    {
    id: '16',
    level: 1,
    type: 'multiple-choice',
    text: 'A hospital is a place ___ sick people are treated.',
    options: ['where', 'which', 'who'],
    correctAnswer: 'where',
    difficulty: 'easy',
    explanation: 'Use "where" to refer to a place.',
  },
  {
    id: '17',
    level: 1,
    type: 'multiple-choice',
    text: 'I met a man ___ brother is a famous actor.',
    options: ['who', 'whose', 'that'],
    correctAnswer: 'whose',
    difficulty: 'easy',
    explanation: 'Use "whose" to show possession.',
  },
  {
    id: '18',
    level: 1,
    type: 'true-false',
    text: "Is this sentence correct? 'I read the book who you recommended.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'easy',
    explanation: '"Who" is for people. You should use "that" or "which" for a book.',
  },
  {
    id: '19',
    level: 1,
    type: 'multiple-choice',
    text: 'The dog ___ is barking lives in that house.',
    options: ['who', 'that', 'which'],
    correctAnswer: 'that',
    difficulty: 'easy',
    explanation: 'Use "that" or "which" for animals and things.',
  },
  {
    id: '20',
    level: 1,
    type: 'multiple-choice',
    text: 'He is the doctor ___ helped me a lot.',
    options: ['which', 'who', 'whose'],
    correctAnswer: 'who',
    difficulty: 'easy',
    explanation: 'Use "who" for people.',
  },
  // Level 2: Intermediate, Fill-in-the-blank with options
  {
    id: '6',
    level: 2,
    type: 'multiple-choice',
    text: 'She is the artist ___ paintings are famous worldwide.',
    options: ['who', 'whose', 'which'],
    correctAnswer: 'whose',
    difficulty: 'medium',
    explanation: 'Use "whose" to show possession.',
  },
  {
    id: '7',
    level: 2,
    type: 'multiple-choice',
    text: 'I visited the town ___ my father was born.',
    options: ['that', 'where', 'who'],
    correctAnswer: 'where',
    difficulty: 'medium',
    explanation: 'Use "where" to refer to a place.',
  },
  {
    id: '8',
    level: 2,
    type: 'true-false',
    text: "Is this sentence correct? 'The movie, that I saw last night, was boring.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'medium',
    explanation: 'Use "which" (not "that") in non-defining clauses, which are set off by commas.',
  },
  {
    id: '9',
    level: 2,
    type: 'multiple-choice',
    text: 'The reason ___ I am late is because of traffic.',
    options: ['why', 'which', 'who'],
    correctAnswer: 'why',
    difficulty: 'medium',
    explanation: 'Use "why" to refer to a reason.',
  },
  {
    id: '10',
    level: 2,
    type: 'multiple-choice',
    text: 'He finally met the celebrity ___ he had always admired.',
    options: ['which', 'that', 'whom'],
    correctAnswer: 'whom',
    difficulty: 'medium',
    explanation: 'Use "whom" as the object of a verb. (He had admired "her" -> "whom").',
  },
  {
    id: '21',
    level: 2,
    type: 'multiple-choice',
    text: 'I remember the day ___ we first met.',
    options: ['when', 'where', 'which'],
    correctAnswer: 'when',
    difficulty: 'medium',
    explanation: 'Use "when" to refer to a time.',
  },
  {
    id: '22',
    level: 2,
    type: 'true-false',
    text: "Is this sentence correct? 'She complained to the man whom was in charge.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'medium',
    explanation: '"Whom" is an object pronoun. Here, the pronoun is the subject of "was", so it should be "who".',
  },
  {
    id: '23',
    level: 2,
    type: 'multiple-choice',
    text: 'The book, ___ is on the table, is mine.',
    options: ['that', 'which', 'who'],
    correctAnswer: 'which',
    difficulty: 'medium',
    explanation: 'Use "which" in non-defining clauses (set off by commas) to give extra information about a thing.',
  },
  {
    id: '24',
    level: 2,
    type: 'multiple-choice',
    text: 'Do you know the reason ___ the sky is blue?',
    options: ['why', 'that', 'how'],
    correctAnswer: 'why',
    difficulty: 'medium',
    explanation: 'Use "why" after "the reason".',
  },
  {
    id: '25',
    level: 2,
    type: 'multiple-choice',
    text: 'The people to ___ she was speaking did not understand her.',
    options: ['who', 'whom', 'that'],
    correctAnswer: 'whom',
    difficulty: 'medium',
    explanation: 'Use "whom" as the object of a preposition ("to whom").',
  },
  // Level 3: Advanced, Sentence Completion (full sentence)
  {
    id: '11',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: The project received high praise. It was completed ahead of schedule.',
    options: [],
    correctAnswer: 'The project, which was completed ahead of schedule, received high praise.',
    difficulty: 'hard',
    explanation: 'Use "which" in a non-defining clause (set off by commas) to give extra information about a thing.',
  },
  {
    id: '12',
    level: 3,
    type: 'sentence-completion',
    text: 'Rewrite the sentence using a relative clause: He said he was ill. This was not true.',
    options: [],
    correctAnswer: 'He said he was ill, which was not true.',
    difficulty: 'hard',
    explanation: '"Which" can be used to refer to a whole clause.',
  },
  {
    id: '13',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: The students were thrilled. They passed the exam.',
    options: [],
    correctAnswer: 'The students who passed the exam were thrilled.',
    difficulty: 'hard',
    explanation: 'Use "who" to introduce a defining clause about people.',
  },
  {
    id: '14',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: I talked to a person. Their car was blocking the driveway.',
    options: [],
    correctAnswer: 'I talked to the person whose car was blocking the driveway.',
    difficulty: 'hard',
    explanation: 'Use "whose" to show possession (the car belongs to the person).',
  },
  {
    id: '15',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: The committee makes decisions. The decisions are final.',
    options: [],
    correctAnswer: 'The decisions that the committee makes are final.',
    difficulty: 'hard',
    explanation: 'Use "that" or "which" for things in a defining clause. "That" is very common.',
  },
  {
    id: '26',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: This is a matter. It does not concern you.',
    options: [],
    correctAnswer: 'This is a matter that does not concern you.',
    difficulty: 'hard',
    explanation: 'Use "that" or "which" to introduce a defining clause for a thing ("matter").',
  },
  {
    id: '27',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: The manager was very helpful. I complained to them.',
    options: [],
    correctAnswer: 'The manager to whom I complained was very helpful.',
    difficulty: 'hard',
    explanation: 'In formal English, when a preposition precedes the relative pronoun, "whom" must be used for people.',
  },
  {
    id: '28',
    level: 3,
    type: 'true-false',
    text: "Is this sentence correct? 'The building, which it is very old, is being renovated.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'hard',
    explanation: 'The relative pronoun "which" replaces the subject pronoun "it". You cannot use both.',
  },
  {
    id: '29',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: He is an author. I greatly admire his work.',
    options: [],
    correctAnswer: 'He is an author whose work I greatly admire.',
    difficulty: 'hard',
    explanation: 'Use "whose" to show possession, even for things, in formal contexts.',
  },
  {
    id: '30',
    level: 3,
    type: 'sentence-completion',
    text: 'Combine using a relative clause: There were several people present. I knew none of them.',
    options: [],
    correctAnswer: 'There were several people present, none of whom I knew.',
    difficulty: 'hard',
    explanation: 'Use "whom" as the object of a preposition ("of whom").',
  },
];
