import type { AppQuestion } from './types';

export const questions: AppQuestion[] = [
  // Level 1: Easy, Multiple Choice
  {
    id: '1',
    level: 1,
    type: 'multiple-choice',
    text: 'The girl ___ is smiling is my sister.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'who',
    difficulty: 'easy',
    explanation: 'Use "who" for people.',
  },
  {
    id: '2',
    level: 1,
    type: 'multiple-choice',
    text: 'This is the cake ___ I bought yesterday.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'that',
    difficulty: 'easy',
    explanation: 'Use "that" or "which" for things. "That" is very common.',
  },
  {
    id: '3',
    level: 1,
    type: 'true-false',
    text: "Is this sentence correct? 'The car who is red is fast.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'easy',
    explanation: '"Who" is used for people. For a car, you should use "that" or "which".',
  },
  {
    id: '4',
    level: 1,
    type: 'multiple-choice',
    text: 'Do you know the woman ___ lives next door?',
    options: ['who', 'which', 'that'],
    correctAnswer: 'who',
    difficulty: 'easy',
    explanation: 'Use "who" to refer to people.',
  },
  {
    id: '5',
    level: 1,
    type: 'multiple-choice',
    text: 'The phone ___ I lost was new.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'which',
    difficulty: 'easy',
    explanation: 'Use "which" or "that" for things. "Which" is often used for non-essential information, but is correct here too.',
  },
  // Level 2: Intermediate, Fill-in-the-blank
  {
    id: '6',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'She is the artist ___ paintings are famous worldwide.',
    options: ['who', 'whose', 'which'],
    correctAnswer: 'whose',
    difficulty: 'medium',
    explanation: 'Use "whose" to show possession.',
  },
  {
    id: '7',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'I visited the town ___ my father was born.',
    options: ['that', 'where', 'who'],
    correctAnswer: 'where',
    difficulty: 'medium',
    explanation: 'Use "where" to refer to a place.',
  },
  {
    id: '8',
    level: 2,
    type: 'true-false',
    text: "Is this sentence correct? 'The movie, that I saw last night, was boring.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'medium',
    explanation: 'Use "which" (not "that") in non-defining clauses, which are set off by commas.',
  },
  {
    id: '9',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'The reason ___ I am late is because of traffic.',
    options: ['why', 'which', 'who'],
    correctAnswer: 'why',
    difficulty: 'medium',
    explanation: 'Use "why" to refer to a reason.',
  },
  {
    id: '10',
    level: 2,
    type: 'fill-in-the-blank',
    text: 'He finally met the celebrity ___ he had always admired.',
    options: ['which', 'that', 'whom'],
    correctAnswer: 'whom',
    difficulty: 'medium',
    explanation: 'Use "whom" as the object of a verb. (He had admired "her" -> "whom").',
  },
  // Level 3: Advanced, Timed
  {
    id: '11',
    level: 3,
    type: 'timed-choice',
    text: 'The project, ___ was completed ahead of schedule, received high praise.',
    options: ['which', 'that', 'who'],
    correctAnswer: 'which',
    difficulty: 'hard',
    explanation: 'Use "which" in a non-defining clause (set off by commas) to give extra information about a thing.',
  },
  {
    id: '12',
    level: 3,
    type: 'timed-choice',
    text: 'This is the only one of his books ___ is worth reading.',
    options: ['which', 'that', 'who'],
    correctAnswer: 'that',
    difficulty: 'hard',
    explanation: 'Use "that" after superlatives like "the only one".',
  },
  {
    id: '13',
    level: 3,
    type: 'true-false',
    text: "Is this sentence correct? 'The students whom passed the exam were thrilled.'",
    options: ['True', 'False'],
    correctAnswer: 'False',
    difficulty: 'hard',
    explanation: '"Whom" is an object pronoun. Here, the pronoun is the subject of "passed", so it should be "who".',
  },
  {
    id: '14',
    level: 3,
    type: 'timed-choice',
    text: "I talked to the person ___ car was blocking the driveway.",
    options: ['who', 'whose', 'which'],
    correctAnswer: 'whose',
    difficulty: 'hard',
    explanation: 'Use "whose" to show possession (the car belongs to the person).',
  },
  {
    id: '15',
    level: 3,
    type: 'timed-choice',
    text: 'The decisions ___ the committee makes are final.',
    options: ['who', 'which', 'that'],
    correctAnswer: 'that',
    difficulty: 'hard',
    explanation: 'Use "that" or "which" for things in a defining clause. "That" is very common.',
  },
];
